#!/bin/bash
#
# createPost
# Copyright 2015 Joe Friedrichsen
# Licensed under the MIT License

if test $# -ne 1; then
  echo "Usage: createPost 'Pretty Name'"
  exit 1
fi

newPostPrettyName="$1"
newPostSlugName="$(echo -n "${newPostPrettyName}" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z)"

currentYear=$(date +%Y)
currentMonth=$(date +%m)
currentDay=$(date +%d)

newPostFullSlug="${currentYear}-${currentMonth}-${currentDay}-${newPostSlugName}"

gitRepoRoot="$(git rev-parse --show-toplevel)"
newPostFileName="${gitRepoRoot}/_posts/${newPostFullSlug}.md"

mkdir -p "${gitRepoRoot}/_posts"
cat > "${newPostFileName}" <<-new-post-entry
---
layout: post
title: ${newPostPrettyName}
tags: []
---
new-post-entry

echo "Created new post! Use 'git add' on this file:"
echo "  git add \"${newPostFileName}\""
